### ISSUE TITLE
Great Project

### ISSUE THREAD

**Issue by 17ss** [SitoCH/hyperliquid-telegram-bot#3]
Hello, this is a great project, I'm really enjoying using it, thank you for your work. I've noticed it sometimes crashes, and I suspect it's related to network connectivity. Would it be possible to add an automatic reconnection feature so it can continue working instead of closing?

```
(base) chang@passivbot:~$ conda activate hyperliquid-telegram-bot
(hyperliquid-telegram-bot) chang@passivbot:~$ cd hyperliquid-telegram-bot
(hyperliquid-telegram-bot) chang@passivbot:~/hyperliquid-telegram-bot$ bash run.sh
2024-12-22 14:28:20,494 - websocket - INFO - Websocket connected
2024-12-22 14:28:20,694 - logging_utils - INFO - Exchange orders disabled
2024-12-22 14:28:22,785 - telegram.ext.Application - INFO - Application started
2024-12-22 21:34:05,597 - logging_utils - ERROR - Websocket error: Connection to remote host was lost.
2024-12-22 21:34:05,607 - websocket - ERROR - Connection to remote host was lost. - goodbye
2024-12-22 21:34:05,611 - logging_utils - WARNING - Websocket closed: None
2024-12-22 21:34:07,776 - apscheduler.executors.default - ERROR - Job "send_message_and_exit (trigger: date[2024-12-22 13:34:05 UTC], next run at: 2024-12-22 13:34:05 UTC)" raised an exception
Traceback (most recent call last):
  File "/home/chang/miniconda3/envs/hyperliquid-telegram-bot/lib/python3.10/site-packages/apscheduler/executors/base_py3.py", line 30, in run_coroutine_job
    retval = await job.func(*job.args, **job.kwargs)
  File "/home/chang/miniconda3/envs/hyperliquid-telegram-bot/lib/python3.10/site-packages/telegram/ext/_jobqueue.py", line 240, in job_callback
    await job.run(job_queue.application)
  File "/home/chang/miniconda3/envs/hyperliquid-telegram-bot/lib/python3.10/site-packages/telegram/ext/_jobqueue.py", line 954, in run
    await asyncio.shield(self._run(application))
  File "/home/chang/miniconda3/envs/hyperliquid-telegram-bot/lib/python3.10/site-packages/telegram/ext/_application.py", line 1077, in __run
    loop.run_forever()
  File "/home/chang/miniconda3/envs/hyperliquid-telegram-bot/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/home/chang/miniconda3/envs/hyperliquid-telegram-bot/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/home/chang/miniconda3/envs/hyperliquid-telegram-bot/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/chang/miniconda3/envs/hyperliquid-telegram-bot/lib/python3.10/site-packages/telegram/ext/_jobqueue.py", line 971, in _run
    await self.callback(context)
  File "/home/chang/hyperliquid-telegram-bot/telegram_utils.py", line 129, in send_message_and_exit
    sys.exit()
SystemExit
2024-12-22 21:34:10,041 - telegram.ext.Application - INFO - Application is stopping. This might take a moment.
2024-12-22 21:34:10,055 - telegram.ext.Application - INFO - Application.stop() complete
Exception in thread Thread-2 (send_ping):
Traceback (most recent call last):
  File "/home/chang/miniconda3/envs/hyperliquid-telegram-bot/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/chang/miniconda3/envs/hyperliquid-telegram-bot/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/chang/miniconda3/envs/hyperliquid-telegram-bot/lib/python3.10/site-packages/hyperliquid/websocket_manager.py", line 81, in send_ping
    self.ws.send(json.dumps({"method": "ping"}))
  File "/home/chang/miniconda3/envs/hyperliquid-telegram-bot/lib/python3.10/site-packages/websocket/_app.py", line 291, in send
    raise WebSocketConnectionClosedException("Connection is already closed.")
websocket._exceptions.WebSocketConnectionClosedException: Connection is already closed.

(hyperliquid-telegram-bot) chang@passivbot:~/hyperliquid-telegram-bot$
(hyperliquid-telegram-bot) chang@passivbot:~/hyperliquid-telegram-bot$ bash run.sh
2024-12-22 21:52:17,037 - websocket - INFO - Websocket connected
2024-12-22 21:52:17,763 - logging_utils - INFO - Exchange orders disabled
2024-12-22 21:52:19,948 - telegram.ext.Application - INFO - Application started
2024-12-23 03:30:43,861 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/chang/miniconda3/envs/hyperliquid-telegram-bot/lib/python3.10/site-packages/httpx/_transports/default.py", line 101, in map_httpcore_exceptions
    yield
  File "/home/chang/miniconda3/envs/hyperliquid-telegram-bot/lib/python3.10/site-packages/httpx/_transports/default.py", line 394, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "/home/chang/miniconda3/envs/hyperliquid-telegram-bot/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 256, in handle_async_request
    raise exc from None
  File "/home/chang/miniconda3/envs/hyperliquid-telegram-bot/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 236, in handle_async_request
    response = await connection.handle_async_request(
  File "/home/chang/miniconda3/envs/hyperliquid-telegram-bot/lib/python3.10/site-packages/httpcore/_async/connection.py", line 103, in handle_async_request
    return await self._connection.handle_async_request(request)
  File "/home/chang/miniconda3/envs/hyperliquid-telegram-bot/lib/python3.10/site-packages/httpcore/_async/http11.py", line 136, in handle_async_request
    raise exc
  File "/home/chang/miniconda3/envs/hyperliquid-telegram-bot/lib/python3.10/site-packages/httpcore/_async/http11.py", line 106, in handle_async_request
    ) = await self._receive_response_headers(**kwargs)
  File "/home/chang/miniconda3/envs/hyperliquid-telegram-bot/lib/python3.10/site-packages/httpcore/_async/http11.py", line 177, in _receive_response_headers
    event = await self._receive_event(timeout=timeout)
  File "/home/chang/miniconda3/envs/hyperliquid-telegram-bot/lib/python3.10/site-packages/httpcore/_async/http11.py", line 217, in _receive_event
    data = await self._network_stream.read(
  File "/home/chang/miniconda3/envs/hyperliquid-telegram-bot/lib/python3.10/site-packages/httpcore/_backends/anyio.py", line 32, in read
    with map_exceptions(exc_map):
  File "/home/chang/miniconda3/envs/hyperliquid-telegram-bot/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/chang/miniconda3/envs/hyperliquid-telegram-bot/lib/python3.10/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ReadError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/chang/miniconda3/envs/hyperliquid-telegram-bot/lib/python3.10/site-packages/telegram/request/_httpxrequest.py", line 293, in do_request
    res = await self._client.request(
  File "/home/chang/miniconda3/envs/hyperliquid-telegram-bot/lib/python3.10/site-packages/httpx/_client.py", line 1540, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/home/chang/miniconda3/envs/hyperliquid-telegram-bot/lib/python3.10/site-packages/httpx/_client.py", line 1629, in send
    response = await self._send_handling_auth(
  File "/home/chang/miniconda3/envs/hyperliquid-telegram-bot/lib/python3.10/site-packages/httpx/_client.py", line 1657, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/home/chang/miniconda3/envs/hyperliquid-telegram-bot/lib/python3.10/site-packages/httpx/_client.py", line 1694, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "/home/chang/miniconda3/envs/hyperliquid-telegram-bot/lib/python3.10/site-packages/httpx/_client.py", line 1730, in _send_single_request
    response = await transport.handle_async_request(request)
  File "/home/chang/miniconda3/envs/hyperliquid-telegram-bot/lib/python3.10/site-packages/httpx/_transports/default.py", line 393, in handle_async_request
    with map_httpcore_exceptions():
  File "/home/chang/miniconda3/envs/hyperliquid-telegram-bot/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/chang/miniconda3/envs/hyperliquid-telegram-bot/lib/python3.10/site-packages/httpx/_transports/default.py", line 118, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ReadError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/chang/miniconda3/envs/hyperliquid-telegram-bot/lib/python3.10/site-packages/telegram/ext/_updater.py", line 750, in _network_loop_retry
    if not await do_action():
  File "/home/chang/miniconda3/envs/hyperliquid-telegram-bot/lib/python3.10/site-packages/telegram/ext/_updater.py", line 744, in do_action
    return action_cb_task.result()
  File "/home/chang/miniconda3/envs/hyperliquid-telegram-bot/lib/python3.10/site-packages/telegram/ext/_updater.py", line 371, in polling_action_cb
    updates = await self.bot.get_updates(
  File "/home/chang/miniconda3/envs/hyperliquid-telegram-bot/lib/python3.10/site-packages/telegram/ext/_extbot.py", line 650, in get_updates
    updates = await super().get_updates(
  File "/home/chang/miniconda3/envs/hyperliquid-telegram-bot/lib/python3.10/site-packages/telegram/_bot.py", line 4480, in get_updates
    await self._post(
  File "/home/chang/miniconda3/envs/hyperliquid-telegram-bot/lib/python3.10/site-packages/telegram/_bot.py", line 619, in _post
    return await self._do_post(
  File "/home/chang/miniconda3/envs/hyperliquid-telegram-bot/lib/python3.10/site-packages/telegram/ext/_extbot.py", line 354, in _do_post
    return await super()._do_post(
  File "/home/chang/miniconda3/envs/hyperliquid-telegram-bot/lib/python3.10/site-packages/telegram/_bot.py", line 648, in _do_post
    result = await request.post(
  File "/home/chang/miniconda3/envs/hyperliquid-telegram-bot/lib/python3.10/site-packages/telegram/request/_baserequest.py", line 202, in post
    result = await self._request_wrapper(
  File "/home/chang/miniconda3/envs/hyperliquid-telegram-bot/lib/python3.10/site-packages/telegram/request/_baserequest.py", line 334, in _request_wrapper
    code, payload = await self.do_request(
  File "/home/chang/miniconda3/envs/hyperliquid-telegram-bot/lib/python3.10/site-packages/telegram/request/_httpxrequest.py", line 317, in do_request
    raise NetworkError(f"httpx.{err.__class__.__name__}: {err}") from err
telegram.error.NetworkError: httpx.ReadError:
2024-12-23 15:41:40,750 - logging_utils - ERROR - Websocket error: Connection to remote host was lost.
2024-12-23 15:41:40,755 - websocket - ERROR - Connection to remote host was lost. - goodbye
2024-12-23 15:41:40,758 - logging_utils - WARNING - Websocket closed: None
2024-12-23 15:41:42,839 - apscheduler.executors.default - ERROR - Job "send_message_and_exit (trigger: date[2024-12-23 07:41:41 UTC], next run at: 2024-12-23 07:41:41 UTC)" raised an exception
Traceback (most recent call last):
  File "/home/chang/miniconda3/envs/hyperliquid-telegram-bot/lib/python3.10/site-packages/apscheduler/executors/base_py3.py", line 30, in run_coroutine_job
    retval = await job.func(*job.args, **job.kwargs)
  File "/home/chang/miniconda3/envs/hyperliquid-telegram-bot/lib/python3.10/site-packages/telegram/ext/_jobqueue.py", line 240, in job_callback
    await job.run(job_queue.application)
  File "/home/chang/miniconda3/envs/hyperliquid-telegram-bot/lib/python3.10/site-packages/telegram/ext/_jobqueue.py", line 954, in run
    await asyncio.shield(self._run(application))
  File "/home/chang/miniconda3/envs/hyperliquid-telegram-bot/lib/python3.10/site-packages/telegram/ext/_application.py", line 1077, in __run
    loop.run_forever()
  File "/home/chang/miniconda3/envs/hyperliquid-telegram-bot/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/home/chang/miniconda3/envs/hyperliquid-telegram-bot/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/home/chang/miniconda3/envs/hyperliquid-telegram-bot/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/chang/miniconda3/envs/hyperliquid-telegram-bot/lib/python3.10/site-packages/telegram/ext/_jobqueue.py", line 971, in _run
    await self.callback(context)
  File "/home/chang/hyperliquid-telegram-bot/telegram_utils.py", line 129, in send_message_and_exit
    sys.exit()
SystemExit
2024-12-23 15:41:44,215 - telegram.ext.Application - INFO - Application is stopping. This might take a moment.
2024-12-23 15:41:44,227 - telegram.ext.Application - INFO - Application.stop() complete
Exception in thread Thread-2 (send_ping):
Traceback (most recent call last):
  File "/home/chang/miniconda3/envs/hyperliquid-telegram-bot/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/chang/miniconda3/envs/hyperliquid-telegram-bot/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/chang/miniconda3/envs/hyperliquid-telegram-bot/lib/python3.10/site-packages/hyperliquid/websocket_manager.py", line 81, in send_ping
    self.ws.send(json.dumps({"method": "ping"}))
  File "/home/chang/miniconda3/envs/hyperliquid-telegram-bot/lib/python3.10/site-packages/websocket/_app.py", line 291, in send
    raise WebSocketConnectionClosedException("Connection is already closed.")
websocket._exceptions.WebSocketConnectionClosedException: Connection is already closed.
```

**Comment by SitoCH** [comment]
Hi,
thank you for the suggestion but unfortunately the Hyperliquid SDK requires some workarounds to properly handle the WebSocket thread. I suggest you to use, or build your own, Docker image and leverage the restart policy, it works well in my case.

**Comment by 17ss** [comment]
Okay, since my platform is arm64 and there's no corresponding image on Docker Hub, I'm using conda for now. 
I will build a docker image from the Dockerfile as soon as possible to start hyperliquid-telegram-bot.
thank you very much.

**Comment by SitoCH** [comment]
I changed the build pipeline to publish a multi arch image, feel free to test it: https://hub.docker.com/r/sito/hyperliquid-telegram-bot/tags

**Comment by 17ss** [comment]
Good job, I'm currently using hyperliquid-telegram-bot within a Docker container on my arm64. Thank you for your help.
